"""Offline-validated Hard board bases used for fast runtime variants."""


HARD_BOARD_BASES = (
    {
        'h_walls': (
            (0, 14), (1, 1), (1, 4), (1, 11), (2, 12), (3, 2), (3, 6),
            (3, 15), (4, 13), (5, 3), (5, 5), (5, 6), (5, 10), (5, 15),
            (6, 7), (6, 8), (8, 7), (8, 8), (9, 0), (9, 5), (9, 9),
            (9, 12), (10, 10), (11, 0), (11, 2), (11, 9), (11, 13),
            (12, 11), (13, 4), (14, 1), (14, 14),
        ),
        'v_walls': (
            (0, 3), (0, 5), (1, 1), (1, 14), (2, 3), (2, 11), (3, 11),
            (4, 2), (4, 5), (4, 13), (5, 5), (5, 10), (6, 3), (6, 5),
            (7, 6), (7, 8), (8, 6), (8, 8), (9, 9), (9, 11), (10, 5),
            (10, 9), (11, 2), (11, 9), (11, 12), (13, 3), (13, 11),
            (14, 0), (14, 14), (15, 9), (15, 11),
        ),
        'targets': {
            'Wild_Vortex': (6, 5),
            'Red_Moon': (11, 2),
            'Blue_Moon': (5, 6),
            'Green_Moon': (10, 9),
            'Yellow_Moon': (5, 10),
            'Red_Planet': (4, 2),
            'Blue_Planet': (10, 0),
            'Green_Planet': (2, 12),
            'Yellow_Planet': (5, 5),
            'Red_Star': (11, 13),
            'Blue_Star': (1, 1),
            'Green_Star': (1, 14),
            'Yellow_Star': (15, 10),
            'Red_Gear': (0, 5),
            'Blue_Gear': (5, 15),
            'Green_Gear': (10, 10),
            'Yellow_Gear': (11, 0),
        },
        'robot_positions': {
            'Blue': (5, 1),
            'Yellow': (1, 12),
            'Green': (13, 5),
            'Red': (15, 9),
            'Silver': (15, 0),
        },
        'target_order': (
            'Wild_Vortex', 'Red_Moon', 'Blue_Moon', 'Green_Moon',
            'Yellow_Moon', 'Red_Planet', 'Blue_Planet', 'Green_Planet',
            'Yellow_Planet', 'Red_Star', 'Blue_Star', 'Green_Star',
            'Yellow_Star', 'Red_Gear', 'Blue_Gear', 'Green_Gear',
            'Yellow_Gear',
        ),
        'paths': (
            'Yl Yt Br Yr Yb Bl Gl Gt Gr',
            'Rt St Rl Rt Yl Bl Rb Rr Rb',
            'Bt Bl Yt Rt Rl Yr Bb Br Bb Bl',
            'Rb Rr Gb Gr Yl Yb Gb Yr Gt Gr',
            'Rt Yr Br Rr Bt Rl Bl Yt Yr Yb',
            'Rl Yt Rr Rb Rl Bb Bl Rt Rr',
            'Yl Yb Bb Yl Bt Rb Br Bb Bl',
            'Gl Gt Yr Yb Yr Sr St Yt Gr Gt Gl',
            'Yl Br Bb Br Yb Yr Yt Yl Rt Rl Yt Yr',
            'Yl Yb Rb Rr Rt Bt Br Rr Rb Rl',
            'Rr Rt Bt Bl Bb Yt Bl Bt Br',
            'Gt Gl Sl Sb Gb Gl Yr Gt Gr',
            'Bt Yl Sr Yb Sb Yr Yb Yl Yb',
            'Rl Sr St Rr Gl Rt Rl Rb Rr Rt',
            'Gt Gr Br Bb Br Yt Yr Yt Yl Yt Sl Bb Br',
            'Rb Gb Gr Gt Gr Sb Gb Gr Gt Gl',
            'St Yb Yr Yt Yl Rl Yb Yr Yb Yl',
        ),
        'safe_transforms': (
            (0, False),
            (0, True),
        ),
        'layout_template': 'diagonal',
    },
)
